version: 2


defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: opennetworking/clam-ci

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      # Restore cache for all the packages
      - restore_cache:
          keys:
            - functions-dependencies-{{ checksum "functions/package.json" }}
            - functions-dependencies-
      - restore_cache:
          keys:
            - client-dependencies-{{ checksum "client/package.json" }}
            - client-dependencies-
      - restore_cache:
          keys:
            - common-dependencies-{{ checksum "common/package.json" }}
            - common-dependencies-
      # install the new dependencies for all the packages
      - run: npm --prefix ./functions install
      - run: npm --prefix ./client install
      - run: npm --prefix ./common install
      # run the tests
      - run: npm --prefix ./common test
      - run: npm --prefix ./functions test
      - run: npm --prefix ./client test
      - run:
          name: Upload coverage reports
          command: bash <(curl -s https://codecov.io/bash)
      # update the cache for all the packages
      - save_cache:
          paths:
            - functions/node_modules
          key: functions-dependencies-{{ checksum "functions/package.json" }}
          when: always
      - save_cache:
          paths:
            - client/node_modules
          key: client-dependencies-{{ checksum "client/package.json" }}
          when: always
      - save_cache:
          paths:
            - common/node_modules
          key: common-dependencies-{{ checksum "common/package.json" }}
          when: always
      - persist_to_workspace:
          root: ~/repo
          paths: .

  build:
    <<: *defaults
    environment:
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build the clinet
          command: |
            pushd client
            REACT_APP_FIREBASE_ENV=${FIREBASE_PROJECT_ID} REACT_APP_FIREBASE_API_KEY=${FIREBASE_API_KEY} CI=false npm run build
            popd
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    environment:
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy Client to Firebase
          command: |
            ./firebase-deploy/node_modules/.bin/firebase --project ${FIREBASE_PROJECT_ID} deploy --token=${FIREBASE_DEPLOY_TOKEN} --only firestore,hosting
      - run:
          name: Configure function parameters
          command: |
            ./firebase-deploy/node_modules/.bin/firebase --project ${FIREBASE_PROJECT_ID} --token=${FIREBASE_DEPLOY_TOKEN} functions:config:set github.app_id="${GH_APP_ID}" github.key="${GH_APP_KEY}" github.secret="${GH_APP_SECRET}"
      - run:
          name: Deploy Functions to Firebase
          command: |
            ./firebase-deploy/node_modules/.bin/firebase --project ${FIREBASE_PROJECT_ID} deploy --token=${FIREBASE_DEPLOY_TOKEN} --only functions


workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
