version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # Restore cache for all the packages
      - restore_cache:
          keys:
            - functions-dependencies-{{ checksum "functions/package.json" }}
            - functions-dependencies-
      - restore_cache:
          keys:
            - client-dependencies-{{ checksum "client/package.json" }}
            - client-dependencies-
      - restore_cache:
          keys:
            - common-dependencies-{{ checksum "common/package.json" }}
            - common-dependencies-
      # install the new dependencies for all the packages
      - run: npm --prefix ./functions install
      - run: npm --prefix ./client install
      - run: npm --prefix ./common install
      # update the cache for all the packages
      - save_cache:
          paths:
            - functions/node_modules
          key: functions-dependencies-{{ checksum "functions/package.json" }}
      - save_cache:
          paths:
            - client/node_modules
          key: client-dependencies-{{ checksum "client/package.json" }}
      - save_cache:
          paths:
            - common/node_modules
          key: common-dependencies-{{ checksum "common/package.json" }}
      - run: npm --prefix ./common test
      - run: npm --prefix ./functions test
      - run: npm --prefix ./client test
